import test from 'node:test';
import assert from 'node:assert/strict';
import {DatabaseSync} from 'node:sqlite';
test('local built API: receipt units/time, owner counts, unchanged finances, reminder retry and deduplication',async()=>{
 const sql=new DatabaseSync(':memory:');
 const db={prepare(query){let values=[];return {bind(...v){values=v;return this;},async first(column){const r=sql.prepare(query).get(...values);return column?r?.[column]??null:r??null;},async all(){return {results:sql.prepare(query).all(...values)};},async run(){return {meta:{changes:Number(sql.prepare(query).run(...values).changes)}};}};},async batch(q){const out=[];for(const s of q)out.push(await s.run());return out;},async exec(s){sql.exec(s);return {count:1,duration:0};}};
 const {default:worker}=await import('../dist/server/index.js');
 const env={DB:db,ASSETS:{fetch:async()=>new Response('',{status:404})}},owner={'oai-authenticated-user-email':'owner@reserve-local-test.invalid'};
 const call=(path,body,headers=owner)=>worker.fetch(new Request(`http://localhost${path}`,{method:body?'POST':'GET',headers:{'Content-Type':'application/json',...headers},...(body?{body:JSON.stringify(body)}:{})}),env,{waitUntil(){},passThroughOnException(){}});
 const read=()=>JSON.parse(sql.prepare('SELECT payload FROM app_state WHERE id=?').get('main').payload);
 const RealDate=globalThis.Date,nativeFetch=globalThis.fetch;let clock='2026-09-01T00:00:00Z';
 globalThis.Date=class extends RealDate{constructor(...a){super(...(a.length?a:[clock]));}static now(){return RealDate.parse(clock);}};
 try{
  await call('/api/worker-auth?bootstrap=1');const original=read();
  const seed={...original,vegetableExpenseVersion:1,vegetableExpenseStartedAt:clock,vegetableExpenseSettings:{normPct:6},vegetablePurchases:[],vegetableNotifications:[],inventory:[{id:'c',name:'KARAM',expenseOnly:true,unit:'g',stock:999,unitCost:2,packageName:'kalla',unitsPerPackage:1,packageCost:2}],suppliers:[{id:'n',name:'Nodir aka',openingBalance:0,balance:0}],transactions:[],financialEntries:[],stockMovements:[],sales:[],recipes:[{id:'lavash',name:'Lavash',ingredients:[]}],posOrders:[],deletedItems:[]};
  sql.prepare('UPDATE app_state SET payload=?,updated_at=? WHERE id=?').run(JSON.stringify(seed),'seed','main');
  const buy=(id,date,quantity,amount)=>({inventoryOnly:true,operationId:id,vegetableOnly:true,date,lines:[{name:'KARAM',quantity,unit:'dona',amount,purchasedAt:`${date}T09:00:00+09:00`,remainingBeforePurchase:0}]});
  let response=await call('/api/intake',buy('aaaaaaaa-bbbb-cccc-dddd-000000000111','2026-09-01',4,15000));assert.equal(response.status,200,await response.clone().text());
  clock='2026-09-05T00:00:00Z';const second=buy('aaaaaaaa-bbbb-cccc-dddd-000000000112','2026-09-05',3,13000);
  response=await call('/api/intake',second);assert.equal(response.status,200,await response.clone().text());
  response=await call('/api/intake',second);assert.equal((await response.json()).alreadySaved,true);
  const bought=read();assert.equal(bought.inventory[0].stock,999);assert.equal(bought.suppliers[0].balance,0);assert.deepEqual(bought.transactions,seed.transactions);assert.equal(bought.vegetablePurchases.length,2);assert.equal(bought.financialEntries.filter(e=>e.category==='Sabzavot va sous').length,2);assert.equal(bought.vegetablePurchases.find(p=>p.amount===13000).purchasedAt,'2026-09-05T00:00:00.000Z');
  response=await call('/api/vegetable-expenses');let report=(await response.json()).reserve;assert.equal(report.products[0].rate,1);assert.equal(report.products[0].daysLeft,3);
  assert.equal((await call('/api/vegetable-expenses',{action:'reserveRecipes',inventoryId:'c',recipeIds:['lavash']})).status,200);
  assert.deepEqual(read().purchaseReserveSettings.recipeIdsByInventory.c,['lavash']);
  assert.equal((await call('/api/vegetable-expenses',{action:'reserveRecipes',inventoryId:'c',recipeIds:['bad']})).status,400);
  const count={action:'reserveCount',operationId:'aaaaaaaa-bbbb-cccc-dddd-000000000113',inventoryId:'c',unit:'dona',quantity:3,countedAt:'2026-09-05T09:00:00+09:00'};
  assert.equal((await call('/api/vegetable-expenses',count,{})).status,401);
  assert.equal((await call('/api/vegetable-expenses',{...count,quantity:''})).status,400);
  assert.equal((await call('/api/vegetable-expenses',count)).status,200);assert.equal((await call('/api/vegetable-expenses',count)).status,200);assert.equal(read().purchaseReserveCounts.length,1);
  for(const key of ['inventory','transactions','financialEntries','sales','stockMovements'])assert.deepEqual(read()[key],bought[key]);
  assert.equal((await call('/api/vegetable-expenses',{action:'reserveSettings',enabled:true,leadDays:1})).status,200);
  assert.equal((await call('/api/vegetable-expenses',{action:'reserveSettings',enabled:true,leadDays:99})).status,400);
  sql.exec('CREATE TABLE IF NOT EXISTS telegram_settings (id TEXT PRIMARY KEY,bot_token TEXT,chat_id TEXT,enabled INTEGER NOT NULL DEFAULT 0)');sql.prepare('INSERT OR REPLACE INTO telegram_settings (id,bot_token,chat_id,enabled) VALUES (?,?,?,1)').run('main','reserve-local-token','local-owner');
  const sent=[];let fail=true;
  globalThis.fetch=async(url,options)=>{assert.equal(String(url),'https://api.telegram.org/botreserve-local-token/sendMessage');const body=JSON.parse(options.body);sent.push(body);if(fail&&body.text.includes('Zaxirani tekshiring')){fail=false;return Response.json({ok:false},{status:500});}return Response.json({ok:true});};
  clock='2026-09-07T00:00:00Z';
  assert.equal((await call('/api/vegetable-expenses',{action:'notify'})).status,200);assert.equal(read().purchaseReserveNotifications[0].status,'failed');
  await call('/api/vegetable-expenses',{action:'notify'});assert.equal(read().purchaseReserveNotifications[0].status,'sent');
  await call('/api/vegetable-expenses',{action:'notify'});assert.equal(sent.filter(s=>s.text.includes('Zaxirani tekshiring')).length,2);assert.ok(sent.every(s=>s.chat_id==='local-owner'));
  assert.equal(read().inventory[0].stock,999);assert.equal(read().suppliers[0].balance,0);assert.equal(read().purchaseReserveCounts.length,1);
  const newItem={action:'createProduct',name:'PIYOZ',unit:'kg',operationId:'aaaaaaaa-bbbb-cccc-dddd-000000000114'};
  assert.equal((await call('/api/vegetable-expenses',newItem,{})).status,401);
  const beforeCreate=read();
  response=await call('/api/vegetable-expenses',newItem);assert.equal(response.status,200,await response.clone().text());const newId=(await response.json()).inventoryId;
  response=await call('/api/vegetable-expenses',newItem);assert.equal((await response.json()).alreadySaved,true);
  const created=read().inventory.find(i=>i.id===newId);assert.equal(created.name,'PIYOZ');assert.equal(created.expenseOnly,true);assert.equal(created.unit,'g');assert.equal(created.unitsPerPackage,1000);assert.equal(created.stock,0);
  for(const key of ['sales','stockMovements','transactions','financialEntries'])assert.deepEqual(read()[key],beforeCreate[key]);
  assert.equal((await call('/api/vegetable-expenses',{...newItem,name:' piyoz ',operationId:'aaaaaaaa-bbbb-cccc-dddd-000000000115'})).status,400);
  assert.equal((await call('/api/vegetable-expenses',{...newItem,name:' ',operationId:'aaaaaaaa-bbbb-cccc-dddd-000000000115'})).status,400);
  response=await call('/api/intake',{inventoryOnly:true,operationId:'aaaaaaaa-bbbb-cccc-dddd-000000000116',vegetableOnly:true,date:'2026-09-07',lines:[{name:'PIYOZ',quantity:2,unit:'kg',amount:8000}]});assert.equal(response.status,200,await response.clone().text());
  assert.equal(read().suppliers[0].balance,0);assert.deepEqual(read().transactions,seed.transactions);assert.equal(read().vegetablePurchases.filter(p=>p.inventoryId===newId).length,1);assert.equal(read().inventory.find(i=>i.id===newId).stock,0);
  response=await call('/api/vegetable-expenses',{action:'reserveRecipes',inventoryId:newId,recipeIds:['lavash']});assert.equal(response.status,200);
  assert.deepEqual(read().purchaseReserveSettings.recipeIdsByInventory[newId],['lavash']);
 }finally{globalThis.Date=RealDate;globalThis.fetch=nativeFetch;sql.close();delete globalThis.__HALO_CONTROL_DB__;}
});
