"use client";
import { useEffect, useState } from 'react';
import { seoulCalendarDate, seoulClock } from './lib/business-time';
type Row=Record<string,any>;
const qty=(n:number)=>Number(n).toLocaleString('en-US',{maximumFractionDigits:2});
const won=(n:number)=>`₩${Math.round(n).toLocaleString('en-US')}`;
const when=(at:string)=>new Date(at).toLocaleString('uz-UZ',{timeZone:'Asia/Seoul',month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit'});
export default function PurchaseReservePanel({report,busy,onAction,onPurchase,counts,onRemove}:{report:Row;busy:boolean;onAction:(body:Row)=>Promise<boolean>;onPurchase:()=>void;counts:Row[];onRemove:(kind:"vegetable"|"reserveCount",id:string,label:string)=>void}){
 const [days,setDays]=useState(7),[search,setSearch]=useState('');
 const [count,setCount]=useState<Row|null>(null),[lead,setLead]=useState<string|null>(null);
 const [menu,setMenu]=useState<Row|null>(null),[menuSearch,setMenuSearch]=useState('');
 const [limit,setLimit]=useState(20);
 useEffect(()=>{if(menu||count)document.getElementById(menu?'reserve-menu-editor':'reserve-count-editor')?.scrollIntoView({behavior:'smooth',block:'start'});},[Boolean(menu),Boolean(count)]);
 const products=report.products.filter((p:Row)=>p.name.toLocaleLowerCase().includes(search.toLocaleLowerCase()));
 const total=report.windows.find((w:Row)=>w.days===days);
 const countProduct=report.products.find((p:Row)=>p.key===count?.key);
 const showCount=(p:Row,empty=false)=>setCount({key:p.key,inventoryId:p.inventoryId,unit:p.unit,quantity:empty?'0':'',date:seoulCalendarDate(),time:seoulClock(),operationId:crypto.randomUUID()});
 const saveCount=async()=>{
  if(!count)return;
  if(await onAction({action:'reserveCount',operationId:count.operationId,inventoryId:count.inventoryId,unit:count.unit,quantity:count.quantity,countedAt:`${count.date}T${count.time}:00+09:00`}))setCount(null);
 };
 return <section className="reserve-section" aria-label="Xarid bo‘yicha alohida zaxira">
  <div className="veg-toolbar"><div role="group" aria-label="Xarid tahlili davri">{[[1,'1 KUN'],[3,'3 KUN'],[7,'1 HAFTA'],[15,'15 KUN'],[30,'1 OY']] .map(([n,label])=><button type="button" key={n} aria-pressed={days===n} onClick={()=>setDays(Number(n))}>{label}</button>)}</div><input aria-label="Zaxiradan mahsulot qidirish" placeholder="Mahsulotni topish…" value={search} onChange={e=>{setSearch(e.target.value);setLimit(20);}}/></div>
  <p>Oxirgi {days} kunlik xarid: <b>{won(total?.amount||0)}</b> · Seoul. 1 oy — oxirgi 30 kun. Belgilangan menyu sotilganda taxminiy qoldiq yangilanadi. Haqiqiy qoldiqni «Qancha qoldi?» yoki «Tugadi» orqali tasdiqlaysiz.</p>
  <details className="panel"><summary>Hisob qanday ishlaydi va eslatma sozlamasi</summary><p>Xaridlar orasidagi vaqt va miqdor o‘rtacha tezlikni beradi. Yangi xarid oldingi zaxira tugaganini anglatmaydi. Haqiqiy qoldiq qaydlari bo‘lsa, tizim ularga ustunlik beradi. Ma’lumot kam bo‘lsa “taxmin” deb ko‘rsatiladi.</p><p>Asosiy sarf oxirgi 7 yoki 30 kunlik yakunlangan oraliqlardan olinadi. Tanlangan menyular savdosiga moslashish uchun kamida 3 kunlik tasdiqlangan qoldiq oralig‘i va 2 kunlik savdo kerak. Prognozda kechagi porsiyalar soni 20%, oxirgi 3 kunlik o‘rtacha 50%, 7 kunlik o‘rtacha 30% vazn oladi. Tasdiqlangan sarf tanlangan menyularning sotilgan soniga bo‘linadi. Shu o‘rtacha sarf va yangi sotuvlar taxminiy qoldiqni yangilaydi; ertangi prognoz sur’ati odatiy tezlikning 3 baravaridan oshirilmaydi. Bu boshlang‘ich model, aniq sarf kafolati emas. Dona, vazn va hajm alohida hisoblanadi. Xarid narxi o‘zgarishi miqdor sarfini o‘zgartirmaydi. Savdo summasi va belgilanmagan menyular hisobga kirmaydi. Tanlangan taomlarda mahsulot turlicha miqdorda ishlatilsa, natija umumiy o‘rtacha bo‘ladi. Oyna faol paytda har daqiqada yangilanadi. Tizim faqat HALOga kiritilgan savdoni ko‘radi; yetishmagan savdo kunlarini tekshiring.</p>
   <div className="veg-actions"><label>Tugashidan necha kun oldin?<input type="number" min="0" max="14" step="0.5" value={lead??String(report.leadDays)} onChange={e=>setLead(e.target.value)}/></label><button type="button" disabled={busy||lead===''} onClick={()=>void onAction({action:'reserveSettings',leadDays:Number(lead??report.leadDays),enabled:true})}>Eslatmani yoqish / saqlash</button><button type="button" className="secondary" disabled={busy||!report.enabled} onClick={()=>void onAction({action:'reserveSettings',leadDays:report.leadDays,enabled:false})}>Eslatmani o‘chirish</button></div>
   <p>Eslatma: {report.enabled?'yoqilgan':'o‘chirilgan'}. Telegram tekshiruvi 09:00–21:00 (Seoul), mahsulot uchun kuniga bir marta; yangi xarid yangi hisobni boshlaydi. Sayt yopiq paytda Google Sheets avtomatik yangilashi ishlayotgan bo‘lishi kerak.</p>
  </details>
  {menu && <section id="reserve-menu-editor" className="panel"><h3>{menu.name} · qaysi menyularda ishlatiladi?</h3><p>Shu mahsulot ishlatiladigan taomlarni belgilang. Bir mahsulot uchun bir necha menyu tanlash mumkin. Retsept va uning grammlari o‘zgarmaydi.</p><input aria-label="Menyu qidirish" placeholder="Menyu nomi…" value={menuSearch} onChange={e=>setMenuSearch(e.target.value)}/><div className="reserve-menu-list">{report.recipes.filter((r:Row)=>r.name.toLocaleLowerCase().includes(menuSearch.toLocaleLowerCase())).map((r:Row)=><label key={r.id}><input type="checkbox" disabled={busy} checked={menu.recipeIds.includes(r.id)} onChange={e=>setMenu({...menu,recipeIds:e.target.checked?[...menu.recipeIds,r.id]:menu.recipeIds.filter((id:string)=>id!==r.id)})}/>{r.name}</label>)}</div><p>{menu.recipeIds.length} ta menyu tanlandi.</p><div className="veg-actions"><button type="button" disabled={busy} onClick={async()=>{if(await onAction({action:'reserveRecipes',inventoryId:menu.inventoryId,recipeIds:menu.recipeIds}))setMenu(null);}}>Menyularni saqlash</button><button type="button" className="secondary" disabled={busy} onClick={()=>setMenu(null)}>Bekor qilish</button></div></section>}
  {count && countProduct && <section id="reserve-count-editor" className="panel veg-form"><h3>{countProduct.name} · haqiqiy qoldiq</h3><p>Hozir ko‘rib turgan miqdorni yozing. 0 — tugagan. O‘zingizga qulay birlikni tanlang. Keyingi xarid va sanoqlarni ham shu birlikda kiriting. Bu qayd pul va oddiy ombor qoldig‘ini o‘zgartirmaydi.</p><fieldset disabled={busy}><label>Qoldiq birligi<select aria-label="Qoldiq birligi" value={count.unit} onChange={e=>setCount({...count,unit:e.target.value,quantity:''})}>{[...new Set([count.unit,'dona','kalla','quti','kg','g','litr','ml','banka','paket'])].map(unit=><option key={unit} value={unit}>{unit}</option>)}</select></label><label>Qoldiq · {count.unit}<input type="number" min="0" step="any" value={count.quantity} onChange={e=>setCount({...count,quantity:e.target.value})}/></label><label>Sana<input type="date" max={seoulCalendarDate()} value={count.date} onChange={e=>setCount({...count,date:e.target.value})}/></label><label>Vaqt · Seoul<input type="time" value={count.time} onChange={e=>setCount({...count,time:e.target.value})}/></label></fieldset><div className="veg-actions"><button type="button" disabled={busy||count.quantity===''} onClick={()=>void saveCount()}>Qoldiqni tasdiqlash</button><button type="button" className="secondary" disabled={busy} onClick={()=>setCount(null)}>Bekor qilish</button></div></section>}
  <div className="reserve-grid">{products.slice(0,limit).map((p:Row)=>{
   const w=p.windows.find((r:Row)=>r.days===days);
   const comparison=w.closedPeriod;
   return <article className={`panel reserve-card ${p.reminder?'reserve-low':''}`} key={p.key}>
    <div className="veg-section-head"><h3>{p.name}</h3><span>{p.unit}</span></div>
    <div className="reserve-headline"><strong>{p.empty?'Tugagan deb qayd etilgan':p.rate===0?'Sarf kuzatilmagan':p.daysLeft===null?'Prognoz uchun ma’lumot kam':p.daysLeft===0?'Zaxirani tekshiring':`Taxminan ${qty(p.daysLeft)} kunga yetadi`}</strong><small>{p.depletionAt?`Taxminiy tugash: ${when(p.depletionAt)}`:'Xaridni kiriting; qolganini yoki tugaganini qayd eting.'}</small></div>
    {p.mixedUnits && <p className="veg-notice">Bu mahsulot turli birliklarda olingan. {p.unit} hisobi alohida; boshqa birlikka avtomatik aylantirilmaydi.</p>}
    <dl className="reserve-numbers"><div><dt>{days} kunda kelgan</dt><dd>{qty(w.quantity)} {p.unit}</dd></div><div><dt>{days} kunlik xarid</dt><dd>{won(w.amount)}</dd></div><div><dt>Taxminiy qoldiq</dt><dd>{p.estimatedRemaining===null?'—':`${qty(p.estimatedRemaining)} ${p.unit}`}</dd></div><div><dt>Kunlik o‘rtacha miqdor</dt><dd>{p.rate===null?'—':`${qty(p.rate)} ${p.unit}`}</dd></div><div><dt>Kunlik qiymat · oxirgi narxda</dt><dd>{p.estimatedDailyCost===null?'—':`${won(p.estimatedDailyCost)} · taxmin`}</dd></div><div><dt>Birlik narxining o‘zgarishi</dt><dd>{p.priceChangePct===null?'—':`${p.priceChangePct>0?'+':''}${qty(p.priceChangePct)}%`}</dd></div></dl>
    {p.latest && <p>Oxirgi xarid: <b>{qty(p.latest.quantity)} {p.unit} · {won(p.latest.amount)}</b> · {when(p.latest.at)}.{p.latestBatchDays!==null?` Shu xaridning o‘zi taxminan ${qty(p.latestBatchDays)} kunga yetadi.`:''}</p>}
    <p><b>{p.estimateMode==='learned_menu'?'Menyu savdosi bo‘yicha o‘rgangan taxmin':p.estimateMode==='measured_time'?'Tasdiqlangan qoldiqlar bo‘yicha taxmin':'Xaridlar oralig‘i bo‘yicha boshlang‘ich taxmin'}</b></p>
    <p>{p.basis==='measured'?'Qoldiq qaydlari asosida':'Xaridlar oralig‘i asosida'} · {p.samples} ta oraliq · oxirgi {p.modelDays} kun. {p.balanceBasis==='last_purchase'?'Oldingi qolgan zaxira noma’lum; qoldiq taxmini faqat oxirgi xaridga tegishli.':'Taxmin oxirgi qoldiq qaydidan davom etadi.'}</p>
    <p>{p.salesAdjusted?`Savdoga moslashtirilgan: odatiy sur’atning ${qty(p.demandFactor)} baravari. Tasdiqlangan tarixda bitta tanlangan taomga o‘rtacha ${qty(p.perPortion)} ${p.unit}.`:p.recipeIds.length?'Tanlangan menyularga moslashish uchun tasdiqlangan qoldiq tarixi yetarli emas; hozir vaqt va xaridlar bo‘yicha taxmin.':'Menyular hali belgilanmagan. Menyularni tanlang; hozir vaqt va xaridlar bo‘yicha taxmin.'}</p>
    <p><b>Tanlangan menyular:</b> {p.recipeIds.map((id:string)=>report.recipes.find((r:Row)=>r.id===id)?.name||'O‘chirilgan menyu').join(', ')||'Tanlanmagan'}</p>
    {p.recipeIds.length>0 && <p>Oldingi {days} to‘liq kunda: {qty(p.demand.windows.find((r:Row)=>r.days===days).amount)} ta tanlangan taom. Bugun: {qty(p.demand.todayPortions)} ta.</p>}
    {p.lastConfirmed && <p>Oxirgi qayd: {qty(p.lastConfirmed.quantity)} {p.unit} · {when(p.lastConfirmed.at)}.</p>}
    {p.inconsistent && <p className="veg-alert">Qoldiq va xaridlar mos kelmagan oraliq bor. U sarf tezligiga qo‘shilmadi; tarixni tekshiring.</p>}
    <div className="veg-actions"><button type="button" disabled={busy} onClick={()=>{setMenu({inventoryId:p.inventoryId,name:p.name,recipeIds:[...p.recipeIds]});setMenuSearch('');}}>Menyularni tanlash</button><button type="button" className="secondary" disabled={busy} onClick={()=>showCount(p)}>Qancha qoldi?</button><button type="button" className="secondary" disabled={busy} onClick={()=>showCount(p,true)}>Tugadi</button></div>
    <details><summary>Oldingi davr bilan solishtirish va xaridlar tarixi</summary>{comparison && <div><p><b>{comparison.start} — {comparison.end}</b> · {days} ta to‘liq kun</p><p>Xarid: {qty(comparison.quantity)} {p.unit} · {won(comparison.amount)}. Oldingi {days} kunda: {qty(comparison.previousQuantity)} {p.unit} · {won(comparison.previousAmount)}.</p><p>{!comparison.comparable?'Oldingi davr to‘liq qayd etilmagan; foiz bilan solishtirish uchun ma’lumot kam.':`Miqdor o‘zgarishi: ${comparison.quantityChangePct===null?'oldingi davrda xarid yo‘q':`${comparison.quantityChangePct>0?'+':''}${qty(comparison.quantityChangePct)}%`}. Summa o‘zgarishi: ${comparison.amountChangePct===null?'oldingi davrda xarid yo‘q':`${comparison.amountChangePct>0?'+':''}${qty(comparison.amountChangePct)}%`}.`}</p><p>Bu xaridlar farqi. Katta xaridning o‘zi ko‘proq sarf bo‘lganini bildirmaydi; haqiqiy sarf qoldiq qaydlari bilan aniqlanadi.</p></div>}{p.lastCycle && <p>Oxirgi ikki xarid oralig‘i: {qty(p.lastCycle.days)} kun. Oldingi xarid: {qty(p.lastCycle.quantity)} {p.unit}, {won(p.lastCycle.amount)}. Shu oraliqqa taqsimlansa: {won(p.lastCycle.dailyAmount)} / kun. Bu haqiqiy sarfning tasdig‘i emas.</p>}<p>Tanlangan {days} kunda tugagan oraliqlar: {w.samples}; ularda jami {qty(w.observedDays)} kun kuzatilgan. {w.rate===null?'Sarf tezligi hali aniqlanmadi.':`O‘rtacha ${qty(w.rate)} ${p.unit}/kun.`}</p><div className="veg-table-scroll"><table><thead><tr><th>Sana / vaqt</th><th>Miqdor</th><th>Jami narx</th><th>Yetkazuvchi</th><th>Amal</th></tr></thead><tbody>{p.history.map((h:Row)=><tr key={h.id}><td>{h.purchasedAt?when(h.purchasedAt):`${h.date} · vaqt kiritilmagan`}</td><td>{qty(h.quantity)} {h.unit}</td><td>{won(h.amount)}</td><td>{h.supplierName||'—'}</td><td><button type="button" className="secondary remove-record" onClick={()=>onRemove("vegetable",h.id,`${p.name} · ${won(h.amount)}`)}>Olib tashlash</button></td></tr>)}</tbody></table></div><h4>Qoldiq qaydlari</h4>{counts.filter(c=>c.inventoryId===p.inventoryId&&c.unit===p.unit).slice().sort((a,b)=>b.countedAt.localeCompare(a.countedAt)).map(c=><p key={c.id}>{when(c.countedAt)} · {qty(c.quantity)} {c.unit} · {c.recordedBy} {c.cancelledAt?<span> · Olib tashlangan: {c.cancellationReason}</span>:<button type="button" className="secondary remove-record" onClick={()=>onRemove("reserveCount",c.id,`${p.name} · qoldiq ${qty(c.quantity)} ${c.unit}`)}>Olib tashlash</button>}</p>)}</details>
   </article>;
  })}</div>
  {!products.length && <div className="panel"><p>Hali mahsulot yoki xarid topilmadi. Mahsulotlar sozlamasida alohida hisobni yoqing va birinchi xaridni kiriting.</p><button type="button" onClick={onPurchase}>Xarid kiritish</button></div>}
  {products.length>limit&&<button type="button" className="secondary" onClick={()=>setLimit(n=>n+20)}>Yana ko‘rsatish</button>}
 </section>;
}
