'use client';
import {useState} from 'react';
import {exportKinds} from './lib/report-export';
export default function ReportExportPanel({branchId,onBefore}:{branchId:string;onBefore:()=>Promise<void>}) {
 const [kind,setKind]=useState('suppliers'),[from,setFrom]=useState(''),[to,setTo]=useState(''),[busy,setBusy]=useState(false),[notice,setNotice]=useState('');
 const snapshot=kind==='suppliers'||kind==='inventory';
 const download=async()=>{setBusy(true);setNotice('');try{await onBefore();const q=new URLSearchParams({branch:branchId,kind,from:snapshot?'':from,to:snapshot?'':to});const r=await fetch('/api/report-export?'+q);if(!r.ok){const d=await r.json();throw new Error(d.error||'Yuklanmadi.');}const url=URL.createObjectURL(await r.blob());const a=document.createElement('a');a.href=url;a.download=`HALO_${kind}.csv`;document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),60000);setNotice('Fayl tayyor. Excel yoki Google Sheets bilan oching.');}catch(e){setNotice((e as Error).message);}finally{setBusy(false);}};
 return <details className="panel report-export-panel"><summary>Hisobotni yuklab olish · Excel / CSV</summary><div className="supplier-profile-edit"><label><span>Hisobot turi</span><select value={kind} disabled={busy} onChange={e=>setKind(e.target.value)}>{Object.entries(exportKinds).map(([id,label])=><option key={id} value={id}>{label}</option>)}</select></label>{snapshot?<p>Hozirgi qoldiq yuklanadi.</p>:<><label><span>Boshlanish sanasi (ixtiyoriy)</span><input type="date" value={from} disabled={busy} onChange={e=>setFrom(e.target.value)}/></label><label><span>Tugash sanasi (ixtiyoriy)</span><input type="date" value={to} disabled={busy} onChange={e=>setTo(e.target.value)}/></label></>}<button type="button" className="save" disabled={busy} onClick={()=>void download()}>{busy?'Tayyorlanmoqda…':'CSV faylni yuklab olish'}</button><p>Telegram yordamchi botiga «Eksport» deb yozib ham fayl olishingiz mumkin.</p>{notice&&<p role="status">{notice}</p>}</div></details>;
}
