"use client";
import { useEffect, useMemo, useRef, useState } from 'react';
import { warehouseDocuments, type WarehouseDocument } from './lib/warehouse-records';
import { planIntakeLine } from './lib/unified-intake';
type Row=Record<string,any>;
const list=(v:unknown):Row[]=>Array.isArray(v)?v:[];
const won=(v:number)=>`₩${Math.round(v||0).toLocaleString('en-US')}`;
export default function WarehouseRecordsPanel({state,onSave,onNavigate,onNew,initialId,onOpened,onRemove}:{state:Row;onSave:(body:Row)=>Promise<void>;onNavigate:(tab:string)=>void;onNew:()=>void;initialId?:string;onOpened?:()=>void;onRemove:(id:string,label:string)=>void}) {
 const documents=useMemo(()=>warehouseDocuments(state),[state]);
 const [search,setSearch]=useState(''),[supplier,setSupplier]=useState(''),[from,setFrom]=useState(''),[to,setTo]=useState(''),[limit,setLimit]=useState(40),[view,setView]=useState<'active'|'history'>('active');
 const [selected,setSelected]=useState<WarehouseDocument|null>(null),[mode,setMode]=useState<'edit'|'cancel'>('edit'),[draft,setDraft]=useState<Row>({}),[reason,setReason]=useState(''),[notice,setNotice]=useState(''),[busy,setBusy]=useState(false);
 const lock=useRef(false),operation=useRef(''),dialog=useRef<HTMLDialogElement>(null);
 const supplierName=(id:string)=>list(state.suppliers).find(s=>s.id===id)?.name||'Ko‘rsatilmagan';
 const open=(d:WarehouseDocument,action:'edit'|'cancel')=>{operation.current=crypto.randomUUID();setSelected(d);setMode(action);setReason('');setNotice('');setDraft({date:d.date,supplierId:d.supplierId,supplierName:supplierName(d.supplierId),invoiceNumber:d.record.intakeInvoiceNumber||'',paidAmount:d.paid,accountId:d.payments[0]?.accountId||list(state.accounts)[0]?.id||'',note:d.record.note||'',lines:d.lines.map(l=>({...l,quantity:String(l.quantity),amount:String(l.amount),expenseConfirmed:l.destination==='expense'}))});};
 useEffect(()=>{if(selected&&!dialog.current?.open)dialog.current?.showModal();if(!selected&&dialog.current?.open)dialog.current.close();},[selected]);
 useEffect(()=>{if(!initialId)return;const d=documents.find(d=>d.id===initialId||d.movements.some(m=>m.id===initialId));if(d){if(d.kind==='linked')openSource(d);else open(d,'edit');}onOpened?.();},[initialId]);
 const openSource=(d:WarehouseDocument)=>{if(d.target==='suppliers'){setNotice('Bu eski kirim manba qarziga bog‘langan. Avtomatik tahrir qo‘llanmaydi; asl hujjat va bog‘langan yozuvlarni tekshirish kerak. Alohida takroriy qarzni Yetkazib beruvchilar → Qarz / to‘lovni tahrirlash orqali bekor qiling.');}else onNavigate(d.target);};
 const filtered=useMemo(()=>documents.filter(d=>(!supplier||d.supplierId===supplier)&&(!from||d.date>=from)&&(!to||d.date<=to)&&(!search.trim()||`${d.source} ${d.record.intakeInvoiceNumber||''} ${supplierName(d.supplierId)} ${d.lines.map(l=>l.name).join(' ')}`.toLocaleLowerCase().includes(search.trim().toLocaleLowerCase()))),[documents,supplier,from,to,search,state.suppliers]);
 const lines=list(draft.lines);const amount=mode==='cancel'?0:lines.reduce((n,l)=>n+(Number(l.amount)||0),0);
 const paidAfter=selected?.kind==='intake'?(mode==='cancel'?0:Number(draft.paidAmount)||0):selected?.paid||0;
 const hasDebt=selected&&selected.record.supplierAccounting!=='separate'&&(selected.kind!=='movement'||selected.record.expenseOnlyAtMovement);
 const debtEffects=useMemo(()=>{
  if(!selected||!hasDebt)return [];
  const changes=new Map<string,number>();
  changes.set(selected.supplierId,-selected.amount+(selected.kind==='intake'?selected.paid:0));
  if(mode!=='cancel')changes.set(draft.supplierId,(changes.get(draft.supplierId)||0)+amount-(selected.kind==='intake'?paidAfter:0));
  return [...changes].map(([id,delta])=>{const before=Number(list(state.suppliers).find(s=>s.id===id)?.balance||0);return{id,name:supplierName(id),before,after:before+delta};});
 },[selected,hasDebt,mode,draft.supplierId,amount,paidAfter,state.suppliers]);
 const stockEffects=useMemo(()=>{
  if(!selected)return [];
  const changes=new Map<string,number>();selected.movements.forEach(m=>changes.set(m.inventoryId,(changes.get(m.inventoryId)||0)-Number(m.quantity)));
  if(mode!=='cancel')for(const l of lines){
   const item=list(state.inventory).find(i=>i.id===l.inventoryId||i.name===l.name);if(!item)continue;
   const old=selected.movements.find(m=>m.inventoryId===item.id);let q=Number(l.quantity)||0;
   if(selected.kind==='intake'||selected.record.supplierAccounting==='separate'){try{const planned=planIntakeLine(list(state.inventory),l,String(draft.date),old ? old.expenseOnlyAtMovement===true : undefined);q=planned.destination==='stock'?planned.stockQuantity:0;}catch{q=NaN;}}
   else if(old?.expenseOnlyAtMovement)q=0;
   changes.set(item.id,(changes.get(item.id)||0)+q);
  }
  return [...changes].map(([id,delta])=>{const item=list(state.inventory).find(i=>i.id===id);return {id,name:item?.name||id,unit:item?.unit||'',before:Number(item?.stock||0),after:Number(item?.stock||0)+delta,delta};});
 },[selected,mode,draft,state.inventory]);
 const submit=async()=>{if(lock.current||!selected)return;lock.current=true;setBusy(true);setNotice('');try{await onSave({...draft,action:mode,id:selected.id,expected:selected.fingerprint,operationId:operation.current,reason});setSelected(null);setNotice(mode==='cancel'?'✓ Kirim bekor qilindi. Asl nusxa va sabab tarixda saqlandi.':'✓ Kirim tahrirlandi. Oldingi nusxa va bog‘langan hisoblar tarixda saqlandi.');}catch(e){setNotice(e instanceof Error?e.message:'Amal saqlanmadi.');}finally{lock.current=false;setBusy(false);}};
 const changeLine=(index:number,patch:Row)=>setDraft(d=>({...d,lines:list(d.lines).map((l,i)=>i===index?{...l,...patch}:l)}));
 return <section className="warehouse-records panel" id="warehouse-receipts">
  <div className="warehouse-heading"><div><h2>Kirimlarni boshqarish</h2><p>Mahsulot yoki yetkazib beruvchini toping. Bitta xarid — bitta hujjat.</p></div><button type="button" className="primary" onClick={onNew}>+ Xarid kiritish</button></div>
  <div className="warehouse-tabs" role="group" aria-label="Kirimlar ko‘rinishi"><button type="button" aria-pressed={view==='active'} onClick={()=>setView('active')}>Kirimlar · {documents.length}</button><button type="button" aria-pressed={view==='history'} onClick={()=>setView('history')}>Tahrir va bekor qilish tarixi</button></div>
  {notice&&!selected&&<p className="form-notice" role="status">{notice}</p>}
  {view==='active'?<>
   <div className="warehouse-filters"><label>Qidirish<input type="search" value={search} onChange={e=>{setSearch(e.target.value);setLimit(40);}} placeholder="Mahsulot, yetkazuvchi, chek…"/></label><label>Yetkazib beruvchi<select value={supplier} onChange={e=>setSupplier(e.target.value)}><option value="">Hammasi</option>{list(state.suppliers).map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</select></label><label>Sanadan<input type="date" value={from} onChange={e=>setFrom(e.target.value)}/></label><label>Sanagacha<input type="date" value={to} onChange={e=>setTo(e.target.value)}/></label><button type="button" onClick={()=>{setSearch('');setSupplier('');setFrom('');setTo('');}}>Filtrni tozalash</button></div>
   <p className="warehouse-found">{filtered.length} ta kirim · {won(filtered.reduce((n,d)=>n+d.amount,0))}</p>
   <div className="warehouse-documents">{filtered.slice(0,limit).map(d=><article key={d.id} className="warehouse-document"><div className="warehouse-document-title"><span><b>{supplierName(d.supplierId)}</b><small>{d.date} · {d.source}{d.record.intakeInvoiceNumber?` · № ${d.record.intakeInvoiceNumber}`:''}</small></span><strong>{won(d.amount)}</strong></div><div className="warehouse-document-lines">{d.lines.map((l,i)=><p key={i}><span>{l.name}</span><b>{Number(l.quantity).toLocaleString()} {l.unit}</b><span>{won(Number(l.amount))}</span></p>)}</div><div className="warehouse-document-actions">{d.kind==='linked'?<button type="button" onClick={()=>openSource(d)}>{d.source} hujjatini ochish →</button>:<><button type="button" onClick={()=>open(d,'edit')}>Tahrirlash</button></>}<button type="button" className="danger remove-record" onClick={()=>onRemove(d.id,`${d.date} · ${d.lines.map(l=>l.name).join(', ')} · ${won(d.amount)}`)}>Olib tashlash</button><small>{d.record.supplierAccounting==='separate'||(d.kind==='movement'&&!d.record.expenseOnlyAtMovement)?'Faqat ombor · qarz yozuvi yo‘q':`Kirimdagi to‘lov: ${won(d.paid)}`}</small></div></article>)}</div>
   {!filtered.length&&<p className="warehouse-empty">Bu qidiruv bo‘yicha kirim topilmadi. Sana va filtrlarni tekshiring.</p>}{filtered.length>limit&&<button type="button" onClick={()=>setLimit(n=>n+40)}>Yana 40 ta kirim</button>}
  </>:<><p>Bu oynada bajarilgan o‘zgarishlar va oldingi nusxalar. Avvalgi bekor qilingan yozuvlar ham alohida arxivda saqlanadi.</p><button type="button" onClick={()=>onNavigate('archive')}>Barcha bekor qilinganlar →</button>{list(state.warehouseRevisions).map(r=><details className="warehouse-revision" key={r.id}><summary>{new Date(r.at).toLocaleString('uz-UZ',{timeZone:'Asia/Seoul',year:'numeric',month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit'})} · Seul · {r.action==='cancel'?'Bekor qilindi':'Tahrirlandi'} · {r.before.lines.map((l:Row)=>l.name).join(', ')}</summary><p>{r.actor} · Sabab: {r.reason}</p><div className="warehouse-version-grid"><div><b>Oldingi nusxa · {r.before.date}</b>{r.before.lines.map((l:Row,i:number)=><p key={i}>{l.name}: {l.quantity} {l.unit} · {won(Number(l.amount))}</p>)}<strong>Jami {won(r.before.amount)}</strong></div><div><b>{r.after?'Yangi nusxa':'Kirim bekor qilingan'}</b>{r.after?.lines.map((l:Row,i:number)=><p key={i}>{l.name}: {l.quantity} {l.unit} · {won(Number(l.amount))}</p>)}{r.after&&<strong>Jami {won(r.after.amount)}</strong>}</div></div></details>)}{!list(state.warehouseRevisions).length&&<p>Hozircha bu oynadan tahrir yoki bekor qilish qilinmagan. Eski tarix o‘z joyida.</p>}</>}
  <dialog ref={dialog} className="warehouse-dialog" onCancel={e=>{if(busy)e.preventDefault();else setSelected(null);}}>{selected&&<>
   <div className="warehouse-heading"><div><h2>{mode==='cancel'?'Kirimni bekor qilish':'Kirimni tahrirlash'}</h2><p>{selected.source} · {selected.date}</p></div><button type="button" disabled={busy} onClick={()=>setSelected(null)} aria-label="Yopish">✕</button></div>
   <fieldset disabled={busy} className="warehouse-edit-fields">
    {mode==='edit'&&<><div className="warehouse-filters"><label>Sana<input type="date" value={draft.date} onChange={e=>setDraft({...draft,date:e.target.value})}/></label><label>Yetkazib beruvchi<select value={draft.supplierId} onChange={e=>setDraft({...draft,supplierId:e.target.value,supplierName:supplierName(e.target.value)})}><option value="">Tanlang</option>{list(state.suppliers).map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</select></label></div>
    {lines.map((l,index)=><div className="warehouse-edit-line" key={index}><label>Mahsulot{selected.kind==='intake'?<input list="warehouse-product-names" value={l.name} onChange={e=>{const item=list(state.inventory).find(i=>i.name===e.target.value);changeLine(index,{name:e.target.value,inventoryId:item?.id||'',unit:item?.unit||l.unit,expenseConfirmed:false});}}/>:<select value={l.inventoryId} disabled={selected.record.expenseOnlyAtMovement} onChange={e=>{const i=list(state.inventory).find(i=>i.id===e.target.value)!;changeLine(index,{inventoryId:i.id,name:i.name,unit:i.unit});}}>{list(state.inventory).map(i=><option key={i.id} value={i.id}>{i.name}</option>)}</select>}</label><label>Miqdor<input type="number" min="0.001" step="any" value={l.quantity} onChange={e=>changeLine(index,{quantity:e.target.value})}/></label><label>Birlik{selected.kind==='intake'?<select value={l.unit} onChange={e=>changeLine(index,{unit:e.target.value})}>{[...new Set([l.unit,'dona','g','kg','ml','litr','qadoq','quti','kalla','banka','paket'])].map(u=><option key={u}>{u}</option>)}</select>:<span>{l.unit}</span>}</label><label>Qator jami · ₩<input type="number" min="0" step="1" value={l.amount} onChange={e=>changeLine(index,{amount:e.target.value})}/></label>{selected.kind==='intake'&&<button type="button" disabled={lines.length===1} onClick={()=>setDraft({...draft,lines:lines.filter((_,i)=>i!==index)})}>Qatorni olib tashlash</button>}{selected.kind==='intake'&&!list(state.inventory).some(i=>i.name===l.name)&&<label className="warehouse-expense-check"><input type="checkbox" checked={l.expenseConfirmed===true} onChange={e=>changeLine(index,{expenseConfirmed:e.target.checked})}/> Ombor mahsuloti emas, xarajat sifatida yozilsin</label>}</div>)}
    <datalist id="warehouse-product-names">{list(state.inventory).map(i=><option key={i.id} value={i.name}/>)}</datalist>
    {selected.kind==='intake'&&<><button type="button" onClick={()=>setDraft({...draft,lines:[...lines,{name:'',quantity:'1',unit:'dona',amount:''}]})}>+ Mahsulot qatori</button><div className="warehouse-filters"><label>Kirimda to‘langan · ₩<input type="number" min="0" max={amount} value={draft.paidAmount} onChange={e=>setDraft({...draft,paidAmount:e.target.value})}/></label><label>To‘lov hisobi<select value={draft.accountId} onChange={e=>setDraft({...draft,accountId:e.target.value})}>{list(state.accounts).map(a=><option key={a.id} value={a.id}>{a.name}</option>)}</select></label></div></>}
    </>}
    <div className="warehouse-impact"><h3>Saqlansa nima o‘zgaradi?</h3><p><span>Kirim summasi</span><strong>{won(selected.amount)} → {won(amount)}</strong></p>{hasDebt?debtEffects.map(d=><p key={d.id}><span>{d.name} · qarz qoldig‘i</span><strong>{won(d.before)} → {won(d.after)}{d.after<0?' · avans':''}</strong></p>):<p>Bu oddiy kirimda yetkazuvchi qarzi va to‘lov yozuvi yo‘q.</p>}{selected.kind==='delivery'&&<p>Avval qayd qilingan to‘lov saqlanadi. Ortiqcha to‘lov yetkazuvchidagi avans bo‘lib qoladi.</p>}{selected.kind==='intake'&&<p><span>Shu kirimdagi pul chiqimi</span><strong>{won(selected.paid)} → {won(paidAfter)}</strong></p>}{stockEffects.map(x=><p key={x.id}><span>{x.name}</span><strong className={x.after<0?'negative':''}>{x.before.toLocaleString()} → {Number.isFinite(x.after)?x.after.toLocaleString():'Birlikni tekshiring'} {x.unit}</strong></p>)}<small>Asl nusxa va sabab tarixda qoladi. Saqlash faqat shu hujjatning ombor, xarid, to‘lov va qarz yozuvlariga ta’sir qiladi.</small></div>
    <label>Sabab · majburiy<textarea maxLength={300} rows={2} value={reason} onChange={e=>setReason(e.target.value)} placeholder="Masalan: 30 kg o‘rniga 3 kg kiritilgan"/></label>
    {notice&&<p role="alert" className="form-notice">{notice}</p>}
    <div className="warehouse-dialog-actions"><button type="button" onClick={()=>setSelected(null)}>Ortga</button><button type="button" className={mode==='cancel'?'danger':'primary'} disabled={reason.trim().length<3} onClick={()=>void submit()}>{busy?'Saqlanmoqda…':mode==='cancel'?'Kirimni bekor qilish':'Tahrirni saqlash'}</button></div>
   </fieldset>
  </>}</dialog>
 </section>;
}
