/**
 * HALO monitor menyusi — ekran CSS'i.
 *
 * Bu matn eski digital menyu saytidan (halo-digital-menu…chatgpt.site, 2026-10-05) SO'ZMA-SO'Z olingan:
 * bitta harfi ham o'zgartirilmagan. Ekran ko'rinishi (ranglar, o'lchamlar, kartalar, shrift) shu yerda.
 * O'ZGARTIRMANG — tests/v2-digital-menu.test.mjs bu matnning eski saytdagi bilan aynan bir xilligini tekshiradi.
 * Eski televizor brauzerlari uchun yozilgan: grid, CSS o'zgaruvchilari va tashqi shrift ishlatilmaydi.
 */
export const TV_CSS = `
html,body{width:100%;height:100%;margin:0;overflow:hidden;background:#000;color:#fff;font-family:Arial,Helvetica,sans-serif}
*{box-sizing:border-box}header{height:72px;padding:0 24px;display:flex;align-items:center;justify-content:space-between;background:#000;border-bottom:1px solid #2b2d30}
.brand{display:flex;align-items:center}.mark{width:42px;height:42px;margin-right:12px;display:flex;align-items:center;justify-content:center;border-radius:9px;background:#ffb400;color:#17120a;font-size:25px;font-weight:900}.brand strong{font-size:26px;letter-spacing:2px}.brand span{display:block;margin-top:2px;color:#aaa;font-size:10px}
.screen-name{color:#ffbd24;font-size:19px;font-weight:900;text-transform:uppercase}.fullscreen{height:42px;padding:0 16px;border:2px solid #ffb400;border-radius:8px;background:#ffb400;color:#16110a;font-size:13px;font-weight:900}.fullscreen:focus{outline:4px solid #fff;outline-offset:3px;background:#ffd466}
#stage{height:calc(100% - 118px);position:relative;padding:5px;background:#000}.menu-page{display:none;width:100%;height:100%;flex-wrap:wrap}.menu-page.active{display:flex}.menu-card{height:50%;padding:5px}.rows-1 .menu-card{height:100%}.cols-1 .menu-card{width:100%}.cols-2 .menu-card{width:50%}.cols-3 .menu-card{width:33.333%}.cols-4 .menu-card{width:25%}.card-inner{height:100%;overflow:hidden;border:1px solid #1b1b1b;border-radius:11px;background:#000}.photo{position:relative;height:61%;overflow:hidden;background:#000}.photo img{display:block;width:100%;height:100%;object-fit:contain;object-position:center}.badge{position:absolute;left:10px;top:10px;padding:7px 10px;border-radius:7px;background:#ffb400;color:#17120a;font-size:12px}.soldout{position:absolute;left:0;right:0;top:42%;padding:13px;background:#111;color:#fff;text-align:center;font-size:23px}
.copy{height:39%;padding:10px 13px;display:flex;align-items:stretch;justify-content:space-between;background:#000}.item-text{width:62%;min-width:0}.copy h2{height:31px;margin:0 0 3px;overflow:hidden;color:#fff;font-size:24px;line-height:1.25;white-space:nowrap;text-overflow:ellipsis}.copy p{height:37px;margin:0;overflow:hidden;color:#aeb1b5;font-size:13px;line-height:1.4}.price{width:38%;display:flex;flex-direction:column;align-items:flex-end;justify-content:flex-end;text-align:right}.price strong{display:block;color:#ffb400;font-size:29px;line-height:1;letter-spacing:-1px}.old-price{display:flex;align-items:center;justify-content:flex-end;margin-bottom:5px}.old-price del{color:#888;font-size:13px}.old-price span{margin-left:5px;padding:3px 5px;border-radius:4px;background:#a32222;color:#fff;font-size:10px;font-weight:bold}
.combo-page{padding:5px}.combo-card{width:100%;height:100%;display:flex;overflow:hidden;border:1px solid #292929;border-radius:12px;background:#000}.combo-photo{position:relative;width:61%;height:100%;overflow:hidden;background:#000}.combo-photo img{display:block;width:100%;height:100%;object-fit:cover}.combo-photo>b{position:absolute;left:18px;top:18px;padding:10px 14px;border-radius:8px;background:#ffb400;color:#17120a;font-size:16px}.combo-copy{width:39%;padding:32px;display:flex;flex-direction:column;justify-content:center;background:#000}.combo-copy>span{color:#ffb400;font-size:15px;font-weight:900;letter-spacing:.12em}.combo-copy h2{margin:12px 0 10px;color:#fff;font-size:46px;line-height:1.05}.combo-copy p{margin:0 0 26px;color:#b6b8bc;font-size:19px;line-height:1.45}.combo-copy>div{display:flex;flex-direction:column;align-items:flex-start}.combo-copy strong{color:#ffb400;font-size:54px;line-height:1}.combo-old-price{justify-content:flex-start}.combo-old-price del{font-size:18px}.combo-old-price span{font-size:13px}
.empty{height:100%;display:flex;align-items:center;justify-content:center;color:#aaa;font-size:30px}footer{height:46px;padding:0 24px;display:flex;align-items:center;justify-content:space-between;background:#000;border-top:1px solid #2b2d30;color:#aaa;font-size:12px}footer strong{color:#ffb400;font-size:24px;letter-spacing:.02em}
@media(max-width:1400px){header{height:64px;padding:0 18px}.mark{width:36px;height:36px}.brand strong{font-size:21px}.brand span{display:none}.screen-name{font-size:16px}.fullscreen{height:38px;font-size:11px}#stage{height:calc(100% - 106px);padding:3px}.menu-card{padding:3px}.card-inner{border-radius:8px}.copy{padding:7px 9px}.copy h2{height:25px;font-size:20px}.copy p{height:32px;font-size:11px}.price strong{font-size:24px}.old-price{margin-bottom:3px}.combo-page{padding:3px}.combo-card{border-radius:8px}.combo-copy{padding:22px}.combo-copy h2{font-size:37px}.combo-copy p{font-size:15px;margin-bottom:18px}.combo-copy strong{font-size:43px}.combo-photo>b{left:12px;top:12px;font-size:13px}footer{height:42px;padding:0 18px;font-size:10px}footer strong{font-size:20px}}

/* HALO QUIET MODERN — minimal TV styling with lightweight solid colors. */
header{height:70px;padding:0 22px;border-top:0;border-bottom:1px solid #292b30;background:#0b0c0e}
.mark{width:42px;height:42px;border:0;border-radius:11px;background:#ffb000;color:#14110a;font-size:25px}
.brand strong{font-size:25px;font-weight:900;letter-spacing:3px}.brand span{color:#92969c;font-size:9px;font-weight:700;letter-spacing:1.5px;text-transform:none}
.screen-name{min-width:0;padding:0;border:0;background:transparent;color:#f5f1e8;font-size:18px;letter-spacing:2px;text-align:center}
.fullscreen{height:40px;padding:0 15px;border:1px solid #5e5026;border-radius:10px;background:#131519;color:#ffbf1f;font-size:11px;letter-spacing:0}.fullscreen:focus{outline:3px solid #fff;outline-offset:2px;background:#ffb000;color:#12100b}
#stage{height:calc(100% - 116px);padding:4px;background:#000}.menu-card{padding:4px}
.card-inner,.menu-card:nth-child(3n + 2) .card-inner,.menu-card:nth-child(3n) .card-inner{border:1px solid #292b30;border-top:1px solid #292b30;border-radius:14px;background:#000}
.photo{height:70%;background:#000}.photo img{background:#000;image-rendering:auto;transform:none;transition:none}
.copy{height:30%;padding:9px 13px 8px;border-top:1px solid #24262a;border-left:0;background:#000}
.badge{left:9px;top:9px;padding:6px 9px;border-radius:6px;background:#ffb000;color:#15110a;font-size:10px;letter-spacing:0}
.item-text{width:64%}.copy h2{height:31px;margin-bottom:4px;font-size:24px;font-weight:800;line-height:1.2;letter-spacing:-.5px;text-transform:none}.copy p{height:35px;color:#ffd05a;font-size:15px;font-weight:800}
.menu-page .item-text{display:flex;align-items:center}.menu-page .copy p,.menu-page .variant-table{display:none}
.variant-table{display:none;width:100%;margin-top:20px}.variant-head,.variant-row{width:100%;display:flex;align-items:center}.variant-head{padding:0 10px 7px;color:#aeb1b5;font-size:13px;font-weight:900;letter-spacing:1px}.variant-row{min-height:50px;margin-top:6px;padding:8px 10px;border:1px solid #4a4024;border-radius:8px;background:#121314}.variant-head span:nth-child(1),.variant-row span:nth-child(1){width:42%}.variant-head span:nth-child(2),.variant-row span:nth-child(2){width:23%;text-align:center}.variant-head span:nth-child(3),.variant-row strong{width:35%;text-align:right}.variant-row span{color:#fff;font-size:20px;font-weight:900}.variant-row span:nth-child(2){color:#ffd05a}.variant-row strong{padding:0;background:transparent;color:#ffb000;font-size:25px;font-weight:900;white-space:nowrap}.variant-price{display:flex;flex-direction:column;align-items:flex-end;justify-content:center;line-height:1}.variant-price del{margin-bottom:3px;color:#85898f;font-size:12px;font-weight:800;text-decoration-color:#ff6659;text-decoration-thickness:2px}.variant-price em{color:#ffb000;font-size:25px;font-style:normal;font-weight:900}
.price{width:36%}.price strong{padding:0;background:transparent;color:#ffb000;font-size:29px;letter-spacing:-1px}.old-price span{border-radius:5px}.old-price span.decrease{background:#173e26;color:#8ff2ad}.old-price span.increase{background:#832c27;color:#fff}
.cols-2.rows-2 .card-inner{display:flex}.cols-2.rows-2 .photo{flex:0 0 58%;width:58%;height:100%}.cols-2.rows-2 .copy{flex:1 1 42%;width:42%;height:100%;padding:16px 18px;flex-direction:column;border-top:0;border-left:1px solid #24262a}.cols-2.rows-2 .item-text,.cols-2.rows-2 .price{width:100%}.cols-2.rows-2 .copy h2{height:auto;margin-bottom:8px;white-space:normal}.cols-2.rows-2 .copy p{height:auto;max-height:72px;font-size:15px;line-height:1.45}.cols-2.rows-2 .price{margin-top:auto}.cols-2.rows-2 .price strong{font-size:34px}
.combo-page{padding:4px}.combo-card{border:1px solid #2d3035;border-top:1px solid #2d3035;border-radius:16px;background:#000}
.combo-photo{width:61%;border-right:1px solid #292b30}.combo-photo>b{left:18px;top:18px;padding:9px 13px;border-radius:7px;background:#ffb000;color:#15110a;font-size:14px;letter-spacing:0}
.combo-copy{width:39%;padding:36px;border-left:0;background:#000}.combo-copy>span{color:#ffb000;font-size:13px;letter-spacing:2px}.combo-copy h2{margin:14px 0 10px;font-size:46px;font-weight:800;line-height:1.02;letter-spacing:-1.5px;text-transform:none}.combo-copy p{color:#f0f1f3;font-size:18px;font-weight:600}.combo-copy strong{padding:0;background:transparent;color:#ffb000;font-size:52px}
.daily-offer-page{display:none;width:100%;height:100%;padding:4px}.daily-offer-page.active{display:flex}.daily-offer-page .combo-card{border-color:#34363a}.daily-offer-page .combo-photo{width:68%}.daily-offer-page .combo-copy{width:32%}.daily-offer-page .combo-copy h2{font-size:52px}.daily-offer-page .combo-copy p{color:#ffd05a;font-size:22px;font-weight:800}.daily-offer-page .combo-copy strong{font-size:58px}.daily-offer-page .variant-table{display:block;margin-top:18px}.daily-offer-page .variant-row strong{font-size:24px}
.daily-offer-page .combo-photo>b{left:22px;top:22px;padding:12px 18px;font-size:27px;font-weight:900;letter-spacing:1px}.offer-open .screen-name{color:#ffb000;font-size:28px;letter-spacing:2.5px}
.combo-meta{margin:0 0 22px;display:flex;align-items:center}.combo-meta span{margin-right:9px;padding:8px 11px;border:1px solid #4a4024;border-radius:6px;background:#151619;color:#ffd05a;font-size:15px;font-weight:900;letter-spacing:.4px}
footer{height:46px;padding:0 22px;border-top:1px solid #292b30;background:#0b0c0e;color:#8e9298;font-size:11px;letter-spacing:0}footer strong{padding:0;background:transparent;color:#ffb000;font-size:23px;font-weight:900}
@media(max-width:1400px){header{height:64px;padding:0 17px;border-top:0}.mark{width:36px;height:36px;border-radius:9px;font-size:22px}.brand strong{font-size:21px}.screen-name{min-width:0;padding:0;font-size:15px}.fullscreen{height:37px;font-size:10px}#stage{height:calc(100% - 106px);padding:3px}.menu-card{padding:3px}.card-inner{border-top-width:1px;border-radius:10px}.copy{padding:6px 9px 5px;border-left:0}.copy h2{height:23px;font-size:19px}.copy p{height:30px;font-size:13px;line-height:1.25}.item-text.has-meta p{height:17px}.item-meta{height:24px;margin-top:2px}.item-meta span{margin-right:4px;padding:4px 5px;font-size:12px}.price strong{padding:0;font-size:24px}.cols-2.rows-2 .copy{padding:12px 14px;border-left:1px solid #24262a}.cols-2.rows-2 .copy h2{height:auto;font-size:24px}.cols-2.rows-2 .copy p{height:auto;max-height:60px;font-size:15px;line-height:1.4}.cols-2.rows-2 .item-text.has-meta p{height:20px;white-space:nowrap}.cols-2.rows-2 .item-meta{height:28px}.cols-2.rows-2 .item-meta span{padding:5px 7px;font-size:13px}.cols-2.rows-2 .price strong{font-size:30px}.combo-page{padding:3px}.combo-card{border-top-width:1px;border-radius:11px}.combo-copy{padding:24px}.combo-copy h2{font-size:37px}.combo-copy p{font-size:15px}.combo-copy strong{font-size:43px}.combo-photo>b{left:12px;top:12px;font-size:12px}.daily-offer-page .combo-photo>b{left:16px;top:16px;padding:10px 15px;font-size:23px}.offer-open .screen-name{font-size:23px;letter-spacing:2px}.daily-offer-page .combo-copy{padding:24px}.daily-offer-page .combo-copy h2{font-size:43px}.daily-offer-page .combo-copy p{font-size:18px}.daily-offer-page .combo-copy strong{font-size:48px}.combo-meta{margin-bottom:16px}.combo-meta span{padding:7px 9px;font-size:13px}footer{height:42px;padding:0 17px}footer strong{font-size:20px}}
body.has-set-offer #stage{height:calc(100% - 186px)}
footer.set-strip{height:116px;padding:3px 22px 3px 8px;justify-content:flex-start;border-top:1px solid #34363a;background:#000;color:#fff;letter-spacing:0}
.set-media{flex:0 0 240px;width:240px;height:110px;margin-right:20px;display:flex;flex-direction:column;align-items:center}.set-photo{display:block;width:240px;height:84px;object-fit:cover;object-position:35% 50%;border-radius:8px;background:#000}.set-title{display:block;width:240px;max-width:240px;margin-top:5px;overflow:hidden;color:#fff;font-size:24px;line-height:1;letter-spacing:2px;text-align:center;white-space:nowrap;text-overflow:ellipsis}
.set-copy{flex:0 1 390px;min-width:0;margin-right:22px;padding-left:22px;display:flex;flex-direction:column;justify-content:center;border-left:1px solid #2c2e32}.set-copy .set-price{padding:0;background:transparent;color:#ffb000;font-size:42px;line-height:1;letter-spacing:-1px;white-space:nowrap}.set-copy>span{margin-top:6px;color:#f0f1f3;font-size:15px;font-weight:750;line-height:1.2}
.set-hours{margin-left:auto;color:#fff;font-size:20px;font-weight:900;white-space:nowrap}
@media(max-width:1400px){body.has-set-offer #stage{height:calc(100% - 166px)}footer.set-strip{height:102px;padding:3px 17px 3px 6px}.set-media{flex-basis:220px;width:220px;height:96px;margin-right:16px}.set-photo{width:220px;height:72px;border-radius:7px}.set-title{width:220px;max-width:220px;margin-top:4px;font-size:21px;letter-spacing:1.7px}.set-copy{flex-basis:310px;margin-right:15px;padding-left:17px}.set-copy .set-price{font-size:36px}.set-copy>span{margin-top:5px;font-size:14px}.set-hours{font-size:18px}}
body.offer-open footer{display:none}body.offer-open #stage{height:calc(100% - 70px)}
@media(max-width:1400px){body.offer-open #stage{height:calc(100% - 64px)}}
body.item-focus-open footer{display:none}body.item-focus-open #stage{height:calc(100% - 70px)}.item-focus-open .menu-page.active{display:block}.item-focus-open .menu-page.active .menu-card{display:none}.item-focus-open .menu-page.active .menu-card.item-focus-active{display:block;width:100%;height:100%;padding:4px}.item-focus-active .card-inner{display:flex!important;width:100%;height:100%;border-radius:16px}.item-focus-active .photo{flex:0 0 68%;width:68%;height:100%}.item-focus-active .copy{flex:1 1 32%;width:32%;height:100%;padding:36px;display:flex;flex-direction:column;justify-content:center;border-top:0;border-left:1px solid #292b30}.item-focus-active .item-text,.item-focus-active .price{width:100%}.item-focus-active .item-text{display:block}.item-focus-active .copy h2{height:auto;margin-bottom:14px;font-size:52px;line-height:1.04;white-space:normal}.item-focus-active .copy p{display:block;height:auto;max-height:110px;font-size:22px;line-height:1.4;white-space:normal}.item-focus-active .variant-table{display:block}.item-focus-active .copy>.price{display:none}.item-focus-active .old-price{justify-content:flex-start}
@media(max-width:1400px){body.item-focus-open #stage{height:calc(100% - 64px)}.item-focus-open .menu-page.active .menu-card.item-focus-active{padding:3px}.item-focus-active .card-inner{border-radius:11px}.item-focus-active .photo{flex-basis:67%;width:67%}.item-focus-active .copy{flex-basis:33%;width:33%;padding:25px}.item-focus-active .copy h2{margin-bottom:10px;font-size:42px}.item-focus-active .copy p{max-height:76px;font-size:18px}.item-focus-active .variant-head{font-size:12px}.item-focus-active .variant-row{min-height:44px;padding:7px 8px}.item-focus-active .variant-row span{font-size:18px}.item-focus-active .variant-row strong{font-size:22px}.item-focus-active .variant-price del{font-size:10px}.item-focus-active .variant-price em{font-size:22px}.daily-offer-page .variant-row{min-height:44px;padding:7px 8px}.daily-offer-page .variant-row span{font-size:18px}.daily-offer-page .variant-row strong{font-size:22px}.daily-offer-page .variant-price del{font-size:10px}.daily-offer-page .variant-price em{font-size:22px}}
`;
